schema_version: 1

context:
  name: transformez
  version: "0.5.7"
  python_min: "3.12"

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: a55c90a46d1b5e4525a6785f4a33161a179c3aece452038e9d12d9d6f9e9c74d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - transformez = transformez.cli:transformez_cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - hatch-vcs
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - fetchez >=0.7.0
    - click
    - numpy >1.24
    - pyproj >3.6.1
    - rasterio >1.4.0
    - libgdal-netcdf
    - libgdal-hdf5
    - pyogrio >=0.7.0
    - shapely >=2.0.0
    - scipy

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true
      imports:
        - transformez
  - script:
      - transformez --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/continuous-dems/transformez
  summary: A standalone utility for vertical elevation datum transformations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matth-love
    - mfisher87
